export const operationsWorkflows = [
  {
    id: 'operations',
    chooseWhen: 'General multi-step analysis, investigation, network operations, security review, release/publish, marketing, SEO, or any non-trivial work not matching code, writing, research, or visual.',
    skills: [
      'conventional-commits',
      'finishing-a-development-branch',
      'security-review',
      'security-scan',
      'network-config-validation',
      'marketing-campaign',
      'seo',
    ],
    catalogSkills: [
      'security-review',
      'security-scan',
      'network-config-validation',
      'marketing-campaign',
      'seo',
    ],
    roles: [
      'task',
      'reviewer',
      'scout',
      'ecc-network-architect',
      'ecc-network-config-reviewer',
      'ecc-network-troubleshooter',
      'ecc-security-reviewer',
      'ecc-opensource-sanitizer',
      'ecc-opensource-forker',
      'ecc-opensource-packager',
    ],
    suggestedFlow: [
      'Clarify outcome, authority, and acceptance criteria.',
      'Gather evidence via scout or domain-specific agents.',
      'For complex analysis, delegate to analyzer; for focused work, Main analyzes directly.',
      'Execute via task or domain agents; Main handles simple operations directly.',
      'Review: Main reviews simple results; delegate complex or security-sensitive work to reviewer.',
      'Verify and report with limitations.',
    ],
    scopeNotes: [
      'Network, security, release, and growth work uses ECC catalog skills for domain methods.',
      'Release/publish requires explicit user authorization for commit, push, deploy.',
      'Security review is advisory; it does not execute commands or block.',
    ],
  },
];
