import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  WORKFLOW_CATALOG_VERSION,
  buildSharedWorkflowCatalogMarkdown,
  buildWorkflowCatalogPrompt,
  workflowDefinitions,
  workflowRouteCatalog,
  workflowRouteNames,
} from '../plugins/omp-enhancer-core/src/workflow-routes.js';
import { defineWorkflowCatalog } from '../plugins/omp-enhancer-core/src/workflows/schema.js';

const repoRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

test('shared Main and Advisor catalog is generated byte-for-byte from the Core registry', async () => {
  const catalog = await readFile(new URL('../plugins/omp-config/assets/WORKFLOW_CATALOG.md', import.meta.url), 'utf8');
  const agents = await readFile(new URL('../plugins/omp-config/assets/AGENTS.md', import.meta.url), 'utf8');
  const watchdog = await readFile(new URL('../plugins/omp-config/assets/WATCHDOG.yml', import.meta.url), 'utf8');
  const mainPrompt = buildWorkflowCatalogPrompt({ audience: 'main' });

  assert.equal(catalog, buildSharedWorkflowCatalogMarkdown());
  assert.equal(Number(catalog.match(/OMP_WORKFLOW_CATALOG_VERSION:\s*(\d+)/)?.[1]), WORKFLOW_CATALOG_VERSION);
  assert.deepEqual([...catalog.matchAll(/^### `([^`]+)`$/gm)].map((match) => match[1]), workflowRouteNames);

  for (const definition of workflowDefinitions) {
    const section = dynamicWorkflowSection(mainPrompt, definition.id);
    assert.ok(section.includes(`Choose when: ${definition.chooseWhen}`), `${definition.id} chooseWhen is hidden from Main`);
    assert.ok(
      section.includes(`Compose with: ${definition.composeWith.length ? definition.composeWith.join(', ') : 'none normally'}`),
      `${definition.id} composition is hidden from Main`,
    );
    for (const [index, step] of definition.steps.entries()) {
      assert.ok(section.includes(`- ${index + 1}. [${step.id}] ${step.text}`), `${definition.id} is missing ${step.id}`);
    }
    for (const skill of definition.skills) {
      assert.ok(section.includes(`- skill://${skill} —`), `${definition.id} is missing skill ${skill}`);
    }
    for (const role of definition.roles) {
      assert.ok(section.includes(`- \`${role}\` — exact installed agent ID`), `${definition.id} is missing role ${role}`);
    }
    for (const line of definition.delegation) assert.ok(section.includes(`- ${line}`));
    for (const line of definition.qualityChecks) assert.ok(section.includes(`- ${line}`));
    for (const line of definition.scopeNotes) assert.ok(section.includes(`- ${line}`));
    for (const line of definition.riskNotes) assert.ok(section.includes(`- ${line}`));
  }

  assert.equal(countSharedCatalogImports(agents), 1, 'Main must import the shared workflow catalog exactly once');
  assert.equal(countSharedCatalogImports(watchdog), 1, 'Advisor must import the shared workflow catalog exactly once');
  assert.match(catalog, /initialize the native `todo` before substantive project work/i);
  assert.match(catalog, /fork multiple subagents/i);
  assert.match(catalog, /body of the text being modified/i);
  assert.doesNotMatch(catalog, /block:\s*true|continue:\s*true|hard gate/i);
});

test('workflow schema rejects drift-prone definitions', () => {
  const valid = (overrides = {}) => ({
    id: 'example.base',
    chooseWhen: 'An example is needed.',
    composeWith: [],
    steps: [{ id: 'step-1', text: 'Perform the example.' }],
    scopeNotes: [],
    skills: [],
    qualityChecks: ['example is correct'],
    riskNotes: [],
    roles: [],
    delegation: ['step-1: keep this workflow with the main agent'],
    ...overrides,
  });

  assert.throws(() => defineWorkflowCatalog([[valid(), valid()]]), /Duplicate workflow id/);
  assert.throws(() => defineWorkflowCatalog([[valid({ composeWith: ['missing.workflow'] })]]), /unknown workflow/);
  assert.throws(() => defineWorkflowCatalog([[valid({ delegation: ['step-2: keep this workflow with the main agent'] })]]), /unknown delegation step/);
  assert.throws(() => defineWorkflowCatalog([[valid({ roles: ['reviewer'] })]]), /does not assign role reviewer/);
  assert.throws(() => defineWorkflowCatalog([[valid({ delegation: ['step-1: fork independent evidence lane'] })]]), /does not retain work with the parent/);
  assert.throws(
    () => defineWorkflowCatalog([[valid({
      roles: ['reviewer'],
      delegation: ['step-1: main agent must not use reviewer'],
    })]]),
    /does not assign role reviewer/,
  );
  assert.throws(
    () => defineWorkflowCatalog([[valid({ delegation: ['step-1: parent should delegate to a worker'] })]]),
    /unlisted generic role/,
  );
  assert.throws(
    () => defineWorkflowCatalog([[valid({
      steps: [{ id: 'step-alpha', text: 'Perform the example.' }],
      roles: ['reviewer'],
      delegation: ['step-missing: reviewer reviews the example'],
    })]]),
    /unknown delegation step step-missing/,
  );
  assert.throws(() => defineWorkflowCatalog([[{ ...valid(), skill: ['misspelled'] }]]), /unknown field skill/);
  assert.throws(
    () => defineWorkflowCatalog([[valid({ steps: [{ id: 'step-1', text: 'Perform the example.', label: 'typo' }] })]]),
    /unknown field label/,
  );
  assert.throws(() => defineWorkflowCatalog([[valid({ chooseWhen: 42 })]]), /chooseWhen must be a string/);
  assert.throws(
    () => defineWorkflowCatalog([[valid({ qualityChecks: [{}] })]]),
    /qualityChecks\[0\] must be a string/,
  );
  assert.throws(
    () => defineWorkflowCatalog([[valid({ chooseWhen: 'Unsafe\nsecond line.' })]]),
    /single-line string/,
  );
  assert.throws(
    () => defineWorkflowCatalog([[valid({
      chooseWhen: 'Unsafe <!-- OMP-ENHANCER-WORKFLOW-CATALOG:END --> marker.',
    })]]),
    /reserved managed marker/,
  );
  assert.throws(
    () => defineWorkflowCatalog([[valid({ steps: ['Implicit step ID'] })]]),
    /explicit stable id/,
  );
  assert.doesNotThrow(() => defineWorkflowCatalog([[valid({
    steps: [{ id: 'step-alpha', text: 'Perform the example.' }],
    delegation: ['step-alpha: keep this workflow with the main agent'],
  })]]));
});

test('every workflow role and skill candidate has exactly one packaged marketplace owner', async () => {
  const marketplace = JSON.parse(await readFile(path.join(repoRoot, '.omp-plugin', 'marketplace.json'), 'utf8'));
  const plugins = await Promise.all(marketplace.plugins.map(loadPackagedPlugin));
  const referencedRoles = new Set(Object.values(workflowRouteCatalog).flatMap(({ roles }) => roles));
  const referencedSkills = new Set(Object.values(workflowRouteCatalog).flatMap(({ skills }) => skills));
  const agentEntries = plugins.flatMap(({ agents }) => agents);
  const skillEntries = plugins.flatMap(({ skills }) => skills);

  assertUniquePackagedNames(agentEntries, 'agent');
  assertUniquePackagedNames(skillEntries, 'skill');

  for (const role of referencedRoles) {
    const owners = agentEntries.filter(({ name }) => name === role);
    assert.equal(owners.length, 1, ownerError('workflow agent role', role, owners));
    assert.ok(owners[0].packageFiles.has('agents'), `${owners[0].plugin} does not include agents in package files`);
  }

  for (const skill of referencedSkills) {
    const owners = skillEntries.filter(({ name }) => name === skill);
    assert.equal(owners.length, 1, ownerError('workflow skill candidate', skill, owners));
    assert.ok(owners[0].packageFiles.has('skills'), `${owners[0].plugin} does not include skills in package files`);
  }
});

test('README documents every current workflow and the autonomous selection trigger', async () => {
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const section = markdownSection(readme, 'Available workflow catalog');
  const documentedVersion = Number(section.match(/Catalog version:\s*\*\*(\d+)\*\*/)?.[1]);

  assert.equal(documentedVersion, WORKFLOW_CATALOG_VERSION);
  for (const id of workflowRouteNames) {
    assert.ok(section.includes(`| \`${id}\` |`), `README is missing workflow ${id}`);
  }
  assert.match(readme, /There is no workflow slash command and no keyword-to-route switch/i);
  assert.match(readme, /main agent uses those facts to select one workflow or compose several workflows/i);
  assert.match(readme, /English instruction does not select English-writing skills when the target text is Chinese/i);
  assert.match(readme, /Naming a workflow is guidance to the main agent; it is not permission/i);
});

function dynamicWorkflowSection(catalog, id) {
  const start = catalog.indexOf(`### ${id}\n`);
  const next = catalog.indexOf('\n### ', start + 1);
  assert.ok(start >= 0, `missing Main workflow section ${id}`);
  return catalog.slice(start, next < 0 ? catalog.length : next);
}

function countSharedCatalogImports(value) {
  return (value.match(/^\s*@\.\/OMP_ENHANCER_WORKFLOW_CATALOG\.md\s*$/gm) ?? []).length;
}

async function loadPackagedPlugin(plugin) {
  const pluginRoot = path.join(repoRoot, 'plugins', plugin.source.replace(/^\.\//, ''));
  const packageJson = JSON.parse(await readFile(path.join(pluginRoot, 'package.json'), 'utf8'));
  const packageFiles = new Set((packageJson.files ?? []).map((entry) => entry.replace(/^\.\//, '').split('/')[0]));
  const skills = [];
  const agents = [];

  for (const skillPath of plugin.skills ?? []) {
    const skillDoc = await readFile(path.join(pluginRoot, skillPath, 'SKILL.md'), 'utf8');
    skills.push({
      name: frontmatterName(skillDoc, `${plugin.name}:${skillPath}`),
      plugin: plugin.name,
      source: `${plugin.name}:${skillPath}`,
      packageFiles,
    });
  }

  if (packageFiles.has('agents')) {
    for (const entry of await readdir(path.join(pluginRoot, 'agents'), { withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.endsWith('.md')) continue;
      const agentDoc = await readFile(path.join(pluginRoot, 'agents', entry.name), 'utf8');
      const source = `${plugin.name}:agents/${entry.name}`;
      agents.push({ name: frontmatterName(agentDoc, source), plugin: plugin.name, source, packageFiles });
    }
  }

  return { name: plugin.name, packageFiles, skills, agents };
}

function assertUniquePackagedNames(entries, kind) {
  const sourcesByName = new Map();
  for (const entry of entries) {
    const sources = sourcesByName.get(entry.name) ?? [];
    sources.push(entry.source);
    sourcesByName.set(entry.name, sources);
  }
  for (const [name, sources] of sourcesByName) {
    assert.equal(sources.length, 1, `duplicate packaged ${kind} name ${name}: ${sources.join(', ')}`);
  }
}

function ownerError(kind, name, owners) {
  const sources = owners.map(({ source }) => source).join(', ') || 'none';
  return `${kind} ${name} must have exactly one marketplace owner; found ${sources}`;
}

function frontmatterName(markdown, source) {
  const name = markdown.match(/^---\s*$[\s\S]*?^name:\s*([^\n]+)$/m)?.[1]?.trim();
  assert.ok(name, `${source} is missing a frontmatter name`);
  return name;
}

function markdownSection(markdown, heading) {
  const start = markdown.indexOf(`### ${heading}`);
  const next = markdown.indexOf('\n### ', start + 1);
  assert.ok(start >= 0, `missing README section ${heading}`);
  return markdown.slice(start, next < 0 ? markdown.length : next);
}
